### ISSUE TITLE
Alternate solution for some printers - extract a PPD from the Windows BR-Script driver

### ISSUE THREAD

**Issue by smithjacobj** [alexivkin/brother-in-arms#1]
https://help.brother-usa.com/app/answers/detail/a_id/164936/~/how-to-create-a-brother-ppd-file-for-installation---linux

I'm pretty sure this is just the USB solution for printers that otherwise support driverless printing, but I was tired of my HL-L3210CW running out of memory printing large pictures (I assume it was attempting to scale the images on the printer), so I set up an rpi print server for it. After fiddling with other solutions I stumbled over this and it might be nice to direct other fools like me to this option.

**Comment by alexivkin** [comment]
Thanks for the hint!
