### ISSUE TITLE
Does not work for MFC-L9570CDW

### ISSUE THREAD

**Issue by JStein01** [alexivkin/brother-in-arms#5]
When I run
`$ sudo zsh oh_brother.zsh MFC-L9570CDW`
I get the error
`dpkg-deb: error: 'mfcl9570cdwlpr-1.5.0-0.i386.deb' is not a Debian format archive`

Running on a Raspberry Pi Zero 2 W on Debian Bookworm

**Comment by alexivkin** [comment]
the link that it gets is probably wrong or no longer points to the correct deb file. it's best to check manually
